### ISSUE TITLE
“Sundial.saver” can’t be opened.

### ISSUE THREAD

**Issue by cnxiekun** [wangweicheng7/Sundial#1]
macOS High Sierra

**Comment by wangweicheng7** [comment]
@cnxiekun  
你点击的提示就是 “can`t be opend ”？
我的笔记本也是 macOS High Sierra 10.13.4，安装是正常的。
如果无法安装的话，你也可以使用源码去编译安装。

**Comment by cnxiekun** [comment]
@wangweicheng7 
我点击安装就出现下面情况：
![screen shot 2018-05-26 at 21 00 11](https://user-images.githubusercontent.com/21699650/40576531-d420cd68-612a-11e8-9fb1-fff4b2f86f23.png)
PS: 我已经设置了 Allow apps downloaded from: Anywhere

然后我就尝试用源码编译，但是我没用过 xcode，所以出现以下 error 不知道是不是我操作错误：
![screen shot 2018-05-26 at 21 19 45](https://user-images.githubusercontent.com/21699650/40576537-f5b88de4-612a-11e8-8b70-bee4544114fc.png)

这个会不会跟账号还有权限有关？
![screen shot 2018-05-26 at 21 20 13](https://user-images.githubusercontent.com/21699650/40576556-236588b4-612b-11e8-8739-51c67ba7a76d.png)

**Comment by wangweicheng7** [comment]
https://github.com/wangweicheng7/Sundial/releases/download/1.0.3/Sundial.saver.zip
