### ISSUE TITLE
在这个版本中，你不能使用sundial

### ISSUE THREAD

**Issue by xyx208** [wangweicheng7/Sundial#5]
![8425B278-4D6E-4D3D-800D-BF097730D589](https://user-images.githubusercontent.com/3462451/65401298-cdbfb900-ddf9-11e9-8551-f4ace1327105.png)
大佬，麻烦帮看看这个问题：

在这个版本中，你不能使用sundial
系统版本：10.14.6 (18G87)

辛苦！

**Comment by wangweicheng7** [comment]
https://github.com/wangweicheng7/Sundial/releases/download/1.0.3/Sundial.saver.zip

**Comment by xyx208** [comment]
> https://github.com/wangweicheng7/Sundial/releases/download/1.0.3/Sundial.saver.zip

谢谢大佬的辛苦付出！
